processors:
  resourcedetection:
    detectors: [env, system]
  cumulativetodelta:
  batch:
    send_batch_size: 10000
    timeout: 10s

receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:

exporters:
  debug:
  otlphttp/uptrace:
    endpoint: "${env:UPTRACE_ENDPOINT}"
    headers:
      uptrace-dsn: "${env:UPTRACE_DSN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/uptrace, debug]
    metrics:
      receivers: [otlp]
      processors: [cumulativetodelta, batch]
      exporters: [otlphttp/uptrace, debug]
    metrics/host:
      receivers: [hostmetrics]
      processors: [cumulativetodelta, batch, resourcedetection]
      exporters: [otlphttp/uptrace, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/uptrace, debug]
